/**
 * Auto-generated by connect-api/scripts/sync-degree-plan-pdfs.ts
 * Do not edit by hand — re-run the sync script after adding a year of PDFs.
 */

export type DegreePlanLink = {
  title: string
  filename: string
  href: string
}

export type DegreePlanSection = {
  id: string
  title: string
  links: DegreePlanLink[]
}

export type DegreePlanYear = {
  year: number
  sections: DegreePlanSection[]
}

export const DEGREE_PLANS_CATALOG: DegreePlanYear[] = [
  {
    "year": 2026,
    "sections": [
      {
        "id": "cert",
        "title": "Certificate Programs",
        "links": [
          {
            "title": "Certificate in Anglican Studies",
            "filename": "1-cert-as-anglican-studies2026.pdf",
            "href": "/api/degree-plans/file/2026/1-cert-as-anglican-studies2026.pdf"
          },
          {
            "title": "Certificate in Christian Ministry",
            "filename": "1-cert-chm-christian-ministry2026.pdf",
            "href": "/api/degree-plans/file/2026/1-cert-chm-christian-ministry2026.pdf"
          },
          {
            "title": "Certificate in Church Multiplication",
            "filename": "1-cert-cm-church-multiplication2026.pdf",
            "href": "/api/degree-plans/file/2026/1-cert-cm-church-multiplication2026.pdf"
          },
          {
            "title": "Certificate in Pastoral Care",
            "filename": "1-cert-pc-pastoral-care2026.pdf",
            "href": "/api/degree-plans/file/2026/1-cert-pc-pastoral-care2026.pdf"
          }
        ]
      },
      {
        "id": "mdiv",
        "title": "Master of Divinity",
        "links": [
          {
            "title": "Master of Divinity (MDiv) – Aesthetics and Applied Arts",
            "filename": "2-mdiv-aesthics-and-applied-arts2026.pdf",
            "href": "/api/degree-plans/file/2026/2-mdiv-aesthics-and-applied-arts2026.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Anglican Studies",
            "filename": "2-mdiv-anglican-studies-2026.pdf",
            "href": "/api/degree-plans/file/2026/2-mdiv-anglican-studies-2026.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Biblical Studies",
            "filename": "2-mdiv-biblical-studies2026.pdf",
            "href": "/api/degree-plans/file/2026/2-mdiv-biblical-studies2026.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Chaplaincy",
            "filename": "2-mdiv-chaplaincy2026.pdf",
            "href": "/api/degree-plans/file/2026/2-mdiv-chaplaincy2026.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Christian Discipleship",
            "filename": "2-mdiv-christian-discipleship2026.pdf",
            "href": "/api/degree-plans/file/2026/2-mdiv-christian-discipleship2026.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Christian Leadership",
            "filename": "2-mdiv-christian-leadership2026.pdf",
            "href": "/api/degree-plans/file/2026/2-mdiv-christian-leadership2026.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Church Planting",
            "filename": "2-mdiv-church-planting2026.pdf",
            "href": "/api/degree-plans/file/2026/2-mdiv-church-planting2026.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Ethics and Social Responsibility",
            "filename": "2-mdiv-ethics-and-social-responsibility2026.pdf",
            "href": "/api/degree-plans/file/2026/2-mdiv-ethics-and-social-responsibility2026.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Intercultural Studies",
            "filename": "2-mdiv-intercultural-studies2026.pdf",
            "href": "/api/degree-plans/file/2026/2-mdiv-intercultural-studies2026.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – No Specialization",
            "filename": "2-mdiv-no-specialization2026.pdf",
            "href": "/api/degree-plans/file/2026/2-mdiv-no-specialization2026.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Pastoral Counseling",
            "filename": "2-mdiv-pastoral-counseling2026.pdf",
            "href": "/api/degree-plans/file/2026/2-mdiv-pastoral-counseling2026.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Spiritual Formation",
            "filename": "2-mdiv-spiritual-formation2026.pdf",
            "href": "/api/degree-plans/file/2026/2-mdiv-spiritual-formation2026.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Theological Studies",
            "filename": "2-mdiv-theological-studies2026.pdf",
            "href": "/api/degree-plans/file/2026/2-mdiv-theological-studies2026.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Theology and Wesleyan Studies",
            "filename": "2-mdiv-theology-and-wesleyan-studies2026.pdf",
            "href": "/api/degree-plans/file/2026/2-mdiv-theology-and-wesleyan-studies2026.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Youth Ministry",
            "filename": "2-mdiv-youth-ministry2026.pdf",
            "href": "/api/degree-plans/file/2026/2-mdiv-youth-ministry2026.pdf"
          }
        ]
      },
      {
        "id": "academic-ma",
        "title": "Academic Master’s",
        "links": [
          {
            "title": "Master of Arts in Biblical Studies (MABS)",
            "filename": "3-mabs-2026.pdf",
            "href": "/api/degree-plans/file/2026/3-mabs-2026.pdf"
          },
          {
            "title": "Master of Arts in Intercultural Studies (MAIS)",
            "filename": "3-mais-2026.pdf",
            "href": "/api/degree-plans/file/2026/3-mais-2026.pdf"
          },
          {
            "title": "Master of Arts in Spiritual Direction (MASD)",
            "filename": "3-masd-2026.pdf",
            "href": "/api/degree-plans/file/2026/3-masd-2026.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Aesthetics and Applied Arts",
            "filename": "3-mats-aesthetics-and-applied-arts2026.pdf",
            "href": "/api/degree-plans/file/2026/3-mats-aesthetics-and-applied-arts2026.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Anglican Studies",
            "filename": "3-mats-anglican-studies2026.pdf",
            "href": "/api/degree-plans/file/2026/3-mats-anglican-studies2026.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Ethics and Social",
            "filename": "3-mats-ethics-and-social2026.pdf",
            "href": "/api/degree-plans/file/2026/3-mats-ethics-and-social2026.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Philosophy & Apologetics",
            "filename": "3-mats-philosophy-apologetics2026.pdf",
            "href": "/api/degree-plans/file/2026/3-mats-philosophy-apologetics2026.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Spiritual Formation",
            "filename": "3-mats-spiritual-formation2026.pdf",
            "href": "/api/degree-plans/file/2026/3-mats-spiritual-formation2026.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Theology and History",
            "filename": "3-mats-theology-and-history2026.pdf",
            "href": "/api/degree-plans/file/2026/3-mats-theology-and-history2026.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Theology and Wesleyan",
            "filename": "3-mats-theology-and-wesleyan2026.pdf",
            "href": "/api/degree-plans/file/2026/3-mats-theology-and-wesleyan2026.pdf"
          }
        ]
      },
      {
        "id": "professional-ma",
        "title": "Professional Master’s",
        "links": [
          {
            "title": "Master of Arts in Christian Ministries (MACM)",
            "filename": "4-macm-2026.pdf",
            "href": "/api/degree-plans/file/2026/4-macm-2026.pdf"
          },
          {
            "title": "Master of Arts in Christian Ministries (MACM) – GMC",
            "filename": "4-macm-gmc-2026.pdf",
            "href": "/api/degree-plans/file/2026/4-macm-gmc-2026.pdf"
          },
          {
            "title": "Master of Arts in Leadership (MAL) – No Track",
            "filename": "4-mal-no-track-2026.pdf",
            "href": "/api/degree-plans/file/2026/4-mal-no-track-2026.pdf"
          },
          {
            "title": "Master of Arts in Leadership (MAL) – Organizational Leadership",
            "filename": "4-mal-organizational-leadership-2026.pdf",
            "href": "/api/degree-plans/file/2026/4-mal-organizational-leadership-2026.pdf"
          },
          {
            "title": "Master of Arts in Leadership (MAL) – Worship Leadership",
            "filename": "4-mal-worship-leadership-2026.pdf",
            "href": "/api/degree-plans/file/2026/4-mal-worship-leadership-2026.pdf"
          },
          {
            "title": "Master of Arts in Marriage and Family Counseling (MAMF)",
            "filename": "4-mamf-2026.pdf",
            "href": "/api/degree-plans/file/2026/4-mamf-2026.pdf"
          },
          {
            "title": "Master of Arts in Mental Health Counseling (MAMH)",
            "filename": "4-mamh-2026.pdf",
            "href": "/api/degree-plans/file/2026/4-mamh-2026.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Children & Family Ministry",
            "filename": "4-mam-children-family-ministry-2026.pdf",
            "href": "/api/degree-plans/file/2026/4-mam-children-family-ministry-2026.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Church Planting",
            "filename": "4-mam-church-planting-2026.pdf",
            "href": "/api/degree-plans/file/2026/4-mam-church-planting-2026.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Congregational Leadership",
            "filename": "4-mam-congregational-leadership-2026.pdf",
            "href": "/api/degree-plans/file/2026/4-mam-congregational-leadership-2026.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – No Track",
            "filename": "4-mam-no-track-2026.pdf",
            "href": "/api/degree-plans/file/2026/4-mam-no-track-2026.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Pastoral Care",
            "filename": "4-mam-pastoral-care-2026.pdf",
            "href": "/api/degree-plans/file/2026/4-mam-pastoral-care-2026.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Preaching",
            "filename": "4-mam-preaching-2026.pdf",
            "href": "/api/degree-plans/file/2026/4-mam-preaching-2026.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Worship",
            "filename": "4-mam-worship-2026.pdf",
            "href": "/api/degree-plans/file/2026/4-mam-worship-2026.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Youth & Family Ministry",
            "filename": "4-mam-youth-family-ministry-2026.pdf",
            "href": "/api/degree-plans/file/2026/4-mam-youth-family-ministry-2026.pdf"
          },
          {
            "title": "Master of Arts in Pastoral Counseling (MAPC) – Chaplaincy",
            "filename": "4-mapc-chaplaincy-2026.pdf",
            "href": "/api/degree-plans/file/2026/4-mapc-chaplaincy-2026.pdf"
          },
          {
            "title": "Master of Arts in Pastoral Counseling (MAPC) – Marriage & Family Pastoral Counselor",
            "filename": "4-mapc-marriage-family-pastoral-counselor-2026.pdf",
            "href": "/api/degree-plans/file/2026/4-mapc-marriage-family-pastoral-counselor-2026.pdf"
          },
          {
            "title": "Master of Arts in Pastoral Counseling (MAPC) – No Track",
            "filename": "4-mapc-no-track-2026.pdf",
            "href": "/api/degree-plans/file/2026/4-mapc-no-track-2026.pdf"
          },
          {
            "title": "Master of Arts in Pastoral Studies (MAPS)",
            "filename": "4-maps-2026.pdf",
            "href": "/api/degree-plans/file/2026/4-maps-2026.pdf"
          }
        ]
      },
      {
        "id": "doctoral",
        "title": "Doctoral / Advanced",
        "links": [
          {
            "title": "Doctor of Ministry (DMin)",
            "filename": "5-dmin-2026.pdf",
            "href": "/api/degree-plans/file/2026/5-dmin-2026.pdf"
          },
          {
            "title": "Doctor of Philosophy in Biblical Studies (PhD)",
            "filename": "5-phd-bs-2026.pdf",
            "href": "/api/degree-plans/file/2026/5-phd-bs-2026.pdf"
          },
          {
            "title": "Doctor of Philosophy in Intercultural Studies (PhD) – ALL",
            "filename": "5-phd-is-all2026.pdf",
            "href": "/api/degree-plans/file/2026/5-phd-is-all2026.pdf"
          },
          {
            "title": "Doctor of Philosophy in Intercultural Studies (PhD) – Contextual Studies",
            "filename": "5-phd-is-contextual-studies-2026.pdf",
            "href": "/api/degree-plans/file/2026/5-phd-is-contextual-studies-2026.pdf"
          },
          {
            "title": "Doctor of Philosophy in Intercultural Studies (PhD) – Development Studies",
            "filename": "5-phd-is-development-studies-2026.pdf",
            "href": "/api/degree-plans/file/2026/5-phd-is-development-studies-2026.pdf"
          },
          {
            "title": "Doctor of Philosophy in Intercultural Studies (PhD) – Evangelization Studies",
            "filename": "5-phd-is-evangelization-studies-2026.pdf",
            "href": "/api/degree-plans/file/2026/5-phd-is-evangelization-studies-2026.pdf"
          },
          {
            "title": "Doctor of Philosophy in Intercultural Studies (PhD) – Historical-Theological Studies",
            "filename": "5-phd-is-historical-theological-studies-2026.pdf",
            "href": "/api/degree-plans/file/2026/5-phd-is-historical-theological-studies-2026.pdf"
          },
          {
            "title": "Master of Theology in Biblical Studies (ThM)",
            "filename": "5-thm-bs-2026.pdf",
            "href": "/api/degree-plans/file/2026/5-thm-bs-2026.pdf"
          },
          {
            "title": "Master of Theology in Intercultural Studies (ThM)",
            "filename": "5-thm-is-2026.pdf",
            "href": "/api/degree-plans/file/2026/5-thm-is-2026.pdf"
          },
          {
            "title": "Master of Theology in Theological Studies (ThM)",
            "filename": "5-thm-ts-2026.pdf",
            "href": "/api/degree-plans/file/2026/5-thm-ts-2026.pdf"
          }
        ]
      },
      {
        "id": "other",
        "title": "Other",
        "links": [
          {
            "title": "Master of Biblical and Theological Foundations (MBTF)",
            "filename": "mbtf-2026.pdf",
            "href": "/api/degree-plans/file/2026/mbtf-2026.pdf"
          }
        ]
      }
    ]
  },
  {
    "year": 2025,
    "sections": [
      {
        "id": "cert",
        "title": "Certificate Programs",
        "links": [
          {
            "title": "Certificate in Anglican Studies",
            "filename": "1-cert-as-anglican-studies2025.pdf",
            "href": "/api/degree-plans/file/2025/1-cert-as-anglican-studies2025.pdf"
          },
          {
            "title": "Certificate in Christian Discipleship",
            "filename": "1-cert-cd-christian-discipleship2025.pdf",
            "href": "/api/degree-plans/file/2025/1-cert-cd-christian-discipleship2025.pdf"
          },
          {
            "title": "Certificate in Christian Education",
            "filename": "1-cert-ce-christian-education2025.pdf",
            "href": "/api/degree-plans/file/2025/1-cert-ce-christian-education2025.pdf"
          },
          {
            "title": "Certificate in Christian Studies",
            "filename": "1-cert-cs-christian-studies2025.pdf",
            "href": "/api/degree-plans/file/2025/1-cert-cs-christian-studies2025.pdf"
          },
          {
            "title": "Certificate in Church Multiplication",
            "filename": "1-cert-cm-church-multiplication2025.pdf",
            "href": "/api/degree-plans/file/2025/1-cert-cm-church-multiplication2025.pdf"
          },
          {
            "title": "Certificate in Hispanic Min Formation",
            "filename": "1-cert-hm-hispanic-min-formation2025.pdf",
            "href": "/api/degree-plans/file/2025/1-cert-hm-hispanic-min-formation2025.pdf"
          },
          {
            "title": "Certificate in Intercultural Studies",
            "filename": "1-cert-is-intercultural-studies2025.pdf",
            "href": "/api/degree-plans/file/2025/1-cert-is-intercultural-studies2025.pdf"
          },
          {
            "title": "Certificate in Leadership",
            "filename": "1-cert-ld-leadership2025.pdf",
            "href": "/api/degree-plans/file/2025/1-cert-ld-leadership2025.pdf"
          },
          {
            "title": "Certificate in Ministry Level 1",
            "filename": "1-cert-m1-ministry-level-12025.pdf",
            "href": "/api/degree-plans/file/2025/1-cert-m1-ministry-level-12025.pdf"
          },
          {
            "title": "Certificate in Pastoral Care",
            "filename": "1-cert-pc-pastoral-care2025.pdf",
            "href": "/api/degree-plans/file/2025/1-cert-pc-pastoral-care2025.pdf"
          },
          {
            "title": "Certificate in Youth and Family",
            "filename": "1-cert-ym-youth-and-family2025.pdf",
            "href": "/api/degree-plans/file/2025/1-cert-ym-youth-and-family2025.pdf"
          }
        ]
      },
      {
        "id": "mdiv",
        "title": "Master of Divinity",
        "links": [
          {
            "title": "Master of Divinity (MDiv) – Aesthetics and Applied Arts",
            "filename": "2-mdiv-aesthics-and-applied-arts2025.pdf",
            "href": "/api/degree-plans/file/2025/2-mdiv-aesthics-and-applied-arts2025.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Anglican Studies",
            "filename": "2-mdiv-anglican-studies-2025.pdf",
            "href": "/api/degree-plans/file/2025/2-mdiv-anglican-studies-2025.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Biblical Studies",
            "filename": "2-mdiv-biblical-studies2025.pdf",
            "href": "/api/degree-plans/file/2025/2-mdiv-biblical-studies2025.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Chaplaincy",
            "filename": "2-mdiv-chaplaincy2025.pdf",
            "href": "/api/degree-plans/file/2025/2-mdiv-chaplaincy2025.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Christian Discipleship",
            "filename": "2-mdiv-christian-discipleship2025.pdf",
            "href": "/api/degree-plans/file/2025/2-mdiv-christian-discipleship2025.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Christian Leadership",
            "filename": "2-mdiv-christian-leadership2025.pdf",
            "href": "/api/degree-plans/file/2025/2-mdiv-christian-leadership2025.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Church Planting",
            "filename": "2-mdiv-church-planting2025.pdf",
            "href": "/api/degree-plans/file/2025/2-mdiv-church-planting2025.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Ethics and Social Responsibility",
            "filename": "2-mdiv-ethics-and-social-responsibility2025.pdf",
            "href": "/api/degree-plans/file/2025/2-mdiv-ethics-and-social-responsibility2025.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Intercultural Studies",
            "filename": "2-mdiv-intercultural-studies2025.pdf",
            "href": "/api/degree-plans/file/2025/2-mdiv-intercultural-studies2025.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – No Specialization",
            "filename": "2-mdiv-no-specialization2025.pdf",
            "href": "/api/degree-plans/file/2025/2-mdiv-no-specialization2025.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Pastoral Counseling",
            "filename": "2-mdiv-pastoral-counseling2025.pdf",
            "href": "/api/degree-plans/file/2025/2-mdiv-pastoral-counseling2025.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Spiritual Formation",
            "filename": "2-mdiv-spiritual-formation2025.pdf",
            "href": "/api/degree-plans/file/2025/2-mdiv-spiritual-formation2025.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Theological Studies",
            "filename": "2-mdiv-theological-studies2025.pdf",
            "href": "/api/degree-plans/file/2025/2-mdiv-theological-studies2025.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Theology and Wesleyan Studies",
            "filename": "2-mdiv-theology-and-wesleyan-studies2025.pdf",
            "href": "/api/degree-plans/file/2025/2-mdiv-theology-and-wesleyan-studies2025.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Youth Ministry",
            "filename": "2-mdiv-youth-ministry2025.pdf",
            "href": "/api/degree-plans/file/2025/2-mdiv-youth-ministry2025.pdf"
          }
        ]
      },
      {
        "id": "academic-ma",
        "title": "Academic Master’s",
        "links": [
          {
            "title": "MACSD",
            "filename": "3-macsd-2025.pdf",
            "href": "/api/degree-plans/file/2025/3-macsd-2025.pdf"
          },
          {
            "title": "Master of Arts in Biblical Studies (MABS)",
            "filename": "3-mabs-2025.pdf",
            "href": "/api/degree-plans/file/2025/3-mabs-2025.pdf"
          },
          {
            "title": "Master of Arts in Intercultural Studies (MAIS)",
            "filename": "3-mais-2025.pdf",
            "href": "/api/degree-plans/file/2025/3-mais-2025.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Aesthetics and Applied Arts",
            "filename": "3-mats-aesthetics-and-applied-arts2025.pdf",
            "href": "/api/degree-plans/file/2025/3-mats-aesthetics-and-applied-arts2025.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Anglican Studies",
            "filename": "3-mats-anglican-studies2025.pdf",
            "href": "/api/degree-plans/file/2025/3-mats-anglican-studies2025.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Ethics and Social",
            "filename": "3-mats-ethics-and-social2025.pdf",
            "href": "/api/degree-plans/file/2025/3-mats-ethics-and-social2025.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Philosophy & Apologetics",
            "filename": "3-mats-philosophy-apologetics2025.pdf",
            "href": "/api/degree-plans/file/2025/3-mats-philosophy-apologetics2025.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Spiritual Formation",
            "filename": "3-mats-spiritual-formation2025.pdf",
            "href": "/api/degree-plans/file/2025/3-mats-spiritual-formation2025.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Theology and History",
            "filename": "3-mats-theology-and-history2025.pdf",
            "href": "/api/degree-plans/file/2025/3-mats-theology-and-history2025.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Theology and Wesleyan",
            "filename": "3-mats-theology-and-wesleyan2025.pdf",
            "href": "/api/degree-plans/file/2025/3-mats-theology-and-wesleyan2025.pdf"
          }
        ]
      },
      {
        "id": "professional-ma",
        "title": "Professional Master’s",
        "links": [
          {
            "title": "Master of Arts in Christian Ministries (MACM)",
            "filename": "4-macm-2025.pdf",
            "href": "/api/degree-plans/file/2025/4-macm-2025.pdf"
          },
          {
            "title": "Master of Arts in Christian Ministries (MACM) – GMC",
            "filename": "4-macm-gmc-2025.pdf",
            "href": "/api/degree-plans/file/2025/4-macm-gmc-2025.pdf"
          },
          {
            "title": "Master of Arts in Leadership (MAL) – No Track",
            "filename": "4-mal-no-track-2025.pdf",
            "href": "/api/degree-plans/file/2025/4-mal-no-track-2025.pdf"
          },
          {
            "title": "Master of Arts in Leadership (MAL) – Organizational Leadership",
            "filename": "4-mal-organizational-leadership-2025.pdf",
            "href": "/api/degree-plans/file/2025/4-mal-organizational-leadership-2025.pdf"
          },
          {
            "title": "Master of Arts in Leadership (MAL) – Worship Leadership",
            "filename": "4-mal-worship-leadership-2025.pdf",
            "href": "/api/degree-plans/file/2025/4-mal-worship-leadership-2025.pdf"
          },
          {
            "title": "Master of Arts in Marriage and Family Counseling (MAMF)",
            "filename": "4-mamf-2025.pdf",
            "href": "/api/degree-plans/file/2025/4-mamf-2025.pdf"
          },
          {
            "title": "Master of Arts in Mental Health Counseling (MAMH)",
            "filename": "4-mamh-2025.pdf",
            "href": "/api/degree-plans/file/2025/4-mamh-2025.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Children & Family Ministry",
            "filename": "4-mam-children-family-ministry-2025.pdf",
            "href": "/api/degree-plans/file/2025/4-mam-children-family-ministry-2025.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Church Planting",
            "filename": "4-mam-church-planting-2025.pdf",
            "href": "/api/degree-plans/file/2025/4-mam-church-planting-2025.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Congregational Leadership",
            "filename": "4-mam-congregational-leadership-2025.pdf",
            "href": "/api/degree-plans/file/2025/4-mam-congregational-leadership-2025.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Latino Ministry and Leadership",
            "filename": "4-mam-latino-ministry-and-leadership-2025.pdf",
            "href": "/api/degree-plans/file/2025/4-mam-latino-ministry-and-leadership-2025.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – No Track",
            "filename": "4-mam-no-track-2025.pdf",
            "href": "/api/degree-plans/file/2025/4-mam-no-track-2025.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Pastoral Care",
            "filename": "4-mam-pastoral-care-2025.pdf",
            "href": "/api/degree-plans/file/2025/4-mam-pastoral-care-2025.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Preaching",
            "filename": "4-mam-preaching-2025.pdf",
            "href": "/api/degree-plans/file/2025/4-mam-preaching-2025.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Worship",
            "filename": "4-mam-worship-2025.pdf",
            "href": "/api/degree-plans/file/2025/4-mam-worship-2025.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Youth & Family Ministry",
            "filename": "4-mam-youth-family-ministry-2025.pdf",
            "href": "/api/degree-plans/file/2025/4-mam-youth-family-ministry-2025.pdf"
          },
          {
            "title": "Master of Arts in Pastoral Counseling (MAPC) – Chaplaincy",
            "filename": "4-mapc-chaplaincy-2025.pdf",
            "href": "/api/degree-plans/file/2025/4-mapc-chaplaincy-2025.pdf"
          },
          {
            "title": "Master of Arts in Pastoral Counseling (MAPC) – Marriage & Family Pastoral Counselor",
            "filename": "4-mapc-marriage-family-pastoral-counselor-2025.pdf",
            "href": "/api/degree-plans/file/2025/4-mapc-marriage-family-pastoral-counselor-2025.pdf"
          },
          {
            "title": "Master of Arts in Pastoral Counseling (MAPC) – No Track",
            "filename": "4-mapc-no-track-2025.pdf",
            "href": "/api/degree-plans/file/2025/4-mapc-no-track-2025.pdf"
          },
          {
            "title": "Master of Arts in Pastoral Studies (MAPS)",
            "filename": "4-maps-2025.pdf",
            "href": "/api/degree-plans/file/2025/4-maps-2025.pdf"
          }
        ]
      },
      {
        "id": "doctoral",
        "title": "Doctoral / Advanced",
        "links": [
          {
            "title": "Doctor of Ministry (DMin)",
            "filename": "5-dmin-2025.pdf",
            "href": "/api/degree-plans/file/2025/5-dmin-2025.pdf"
          },
          {
            "title": "Doctor of Philosophy in Biblical Studies (PhD)",
            "filename": "5-phd-bs-2025.pdf",
            "href": "/api/degree-plans/file/2025/5-phd-bs-2025.pdf"
          },
          {
            "title": "Doctor of Philosophy in Intercultural Studies (PhD) – ALL",
            "filename": "5-phd-is-all2025.pdf",
            "href": "/api/degree-plans/file/2025/5-phd-is-all2025.pdf"
          },
          {
            "title": "Doctor of Philosophy in Intercultural Studies (PhD) – Contextual Studies",
            "filename": "5-phd-is-contextual-studies-2025.pdf",
            "href": "/api/degree-plans/file/2025/5-phd-is-contextual-studies-2025.pdf"
          },
          {
            "title": "Doctor of Philosophy in Intercultural Studies (PhD) – Development Studies",
            "filename": "5-phd-is-development-studies-2025.pdf",
            "href": "/api/degree-plans/file/2025/5-phd-is-development-studies-2025.pdf"
          },
          {
            "title": "Doctor of Philosophy in Intercultural Studies (PhD) – Evangelization Studies",
            "filename": "5-phd-is-evangelization-studies-2025.pdf",
            "href": "/api/degree-plans/file/2025/5-phd-is-evangelization-studies-2025.pdf"
          },
          {
            "title": "Doctor of Philosophy in Intercultural Studies (PhD) – Historical-Theological Studies",
            "filename": "5-phd-is-historical-theological-studies-2025.pdf",
            "href": "/api/degree-plans/file/2025/5-phd-is-historical-theological-studies-2025.pdf"
          },
          {
            "title": "Master of Theology in Biblical Studies (ThM)",
            "filename": "5-thm-bs-2025.pdf",
            "href": "/api/degree-plans/file/2025/5-thm-bs-2025.pdf"
          },
          {
            "title": "Master of Theology in Intercultural Studies (ThM)",
            "filename": "5-thm-is-2025.pdf",
            "href": "/api/degree-plans/file/2025/5-thm-is-2025.pdf"
          },
          {
            "title": "Master of Theology in Theological Studies (ThM)",
            "filename": "5-thm-ts-2025.pdf",
            "href": "/api/degree-plans/file/2025/5-thm-ts-2025.pdf"
          }
        ]
      },
      {
        "id": "other",
        "title": "Other",
        "links": [
          {
            "title": "Master of Biblical and Theological Foundations (MBTF)",
            "filename": "mbtf-2025.pdf",
            "href": "/api/degree-plans/file/2025/mbtf-2025.pdf"
          }
        ]
      }
    ]
  },
  {
    "year": 2024,
    "sections": [
      {
        "id": "cert",
        "title": "Certificate Programs",
        "links": [
          {
            "title": "Certificate in Anglican Studies",
            "filename": "1-cert-as-anglican-studies2024.pdf",
            "href": "/api/degree-plans/file/2024/1-cert-as-anglican-studies2024.pdf"
          },
          {
            "title": "Certificate in Christian Discipleship",
            "filename": "1-cert-cd-christian-discipleship2024.pdf",
            "href": "/api/degree-plans/file/2024/1-cert-cd-christian-discipleship2024.pdf"
          },
          {
            "title": "Certificate in Christian Education",
            "filename": "1-cert-ce-christian-education2024.pdf",
            "href": "/api/degree-plans/file/2024/1-cert-ce-christian-education2024.pdf"
          },
          {
            "title": "Certificate in Christian Studies",
            "filename": "1-cert-cs-christian-studies2024.pdf",
            "href": "/api/degree-plans/file/2024/1-cert-cs-christian-studies2024.pdf"
          },
          {
            "title": "Certificate in Church Multiplication",
            "filename": "1-cert-cm-church-multiplication2024.pdf",
            "href": "/api/degree-plans/file/2024/1-cert-cm-church-multiplication2024.pdf"
          },
          {
            "title": "Certificate in Hispanic Min Formation",
            "filename": "1-cert-hm-hispanic-min-formation2024.pdf",
            "href": "/api/degree-plans/file/2024/1-cert-hm-hispanic-min-formation2024.pdf"
          },
          {
            "title": "Certificate in Intercultural Studies",
            "filename": "1-cert-is-intercultural-studies2024.pdf",
            "href": "/api/degree-plans/file/2024/1-cert-is-intercultural-studies2024.pdf"
          },
          {
            "title": "Certificate in Leadership",
            "filename": "1-cert-ld-leadership2024.pdf",
            "href": "/api/degree-plans/file/2024/1-cert-ld-leadership2024.pdf"
          },
          {
            "title": "Certificate in Ministry Level 1",
            "filename": "1-cert-m1-ministry-level-12024.pdf",
            "href": "/api/degree-plans/file/2024/1-cert-m1-ministry-level-12024.pdf"
          },
          {
            "title": "Certificate in Pastoral Care",
            "filename": "1-cert-pc-pastoral-care2024.pdf",
            "href": "/api/degree-plans/file/2024/1-cert-pc-pastoral-care2024.pdf"
          },
          {
            "title": "Certificate in Youth and Family",
            "filename": "1-cert-ym-youth-and-family2024.pdf",
            "href": "/api/degree-plans/file/2024/1-cert-ym-youth-and-family2024.pdf"
          }
        ]
      },
      {
        "id": "mdiv",
        "title": "Master of Divinity",
        "links": [
          {
            "title": "Master of Divinity (MDiv) – Aesthetics and Applied Arts",
            "filename": "2-mdiv-2024-aesthics-and-applied-arts.pdf",
            "href": "/api/degree-plans/file/2024/2-mdiv-2024-aesthics-and-applied-arts.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Anglican Studies",
            "filename": "2-mdiv-2024-anglican-studies.pdf",
            "href": "/api/degree-plans/file/2024/2-mdiv-2024-anglican-studies.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Biblical Studies",
            "filename": "2-mdiv-2024-biblical-studies.pdf",
            "href": "/api/degree-plans/file/2024/2-mdiv-2024-biblical-studies.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Chaplaincy",
            "filename": "2-mdiv-2024-chaplaincy.pdf",
            "href": "/api/degree-plans/file/2024/2-mdiv-2024-chaplaincy.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Christian Discipleship",
            "filename": "2-mdiv-2024-christian-discipleship.pdf",
            "href": "/api/degree-plans/file/2024/2-mdiv-2024-christian-discipleship.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Christian Leadership",
            "filename": "2-mdiv-2024-christian-leadership.pdf",
            "href": "/api/degree-plans/file/2024/2-mdiv-2024-christian-leadership.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Church Planting",
            "filename": "2-mdiv-2024-church-planting.pdf",
            "href": "/api/degree-plans/file/2024/2-mdiv-2024-church-planting.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Ethics and Social Responsibility",
            "filename": "2-mdiv-2024-ethics-and-social-responsibility.pdf",
            "href": "/api/degree-plans/file/2024/2-mdiv-2024-ethics-and-social-responsibility.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Intercultural Studies",
            "filename": "2-mdiv-2024-intercultural-studies.pdf",
            "href": "/api/degree-plans/file/2024/2-mdiv-2024-intercultural-studies.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – No Specialization",
            "filename": "2-mdiv-2024-no-specialization.pdf",
            "href": "/api/degree-plans/file/2024/2-mdiv-2024-no-specialization.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Pastoral Counseling",
            "filename": "2-mdiv-2024-pastoral-counseling.pdf",
            "href": "/api/degree-plans/file/2024/2-mdiv-2024-pastoral-counseling.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Spiritual Formation",
            "filename": "2-mdiv-2024-spiritual-formation.pdf",
            "href": "/api/degree-plans/file/2024/2-mdiv-2024-spiritual-formation.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Theological Studies",
            "filename": "2-mdiv-2024-theological-studies.pdf",
            "href": "/api/degree-plans/file/2024/2-mdiv-2024-theological-studies.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Theology and Wesleyan Studies",
            "filename": "2-mdiv-2024-theology-and-wesleyan-studies.pdf",
            "href": "/api/degree-plans/file/2024/2-mdiv-2024-theology-and-wesleyan-studies.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Youth Ministry",
            "filename": "2-mdiv-2024-youth-ministry.pdf",
            "href": "/api/degree-plans/file/2024/2-mdiv-2024-youth-ministry.pdf"
          }
        ]
      },
      {
        "id": "academic-ma",
        "title": "Academic Master’s",
        "links": [
          {
            "title": "Master of Arts in Biblical Studies (MABS)",
            "filename": "3-mabs-2024.pdf",
            "href": "/api/degree-plans/file/2024/3-mabs-2024.pdf"
          },
          {
            "title": "Master of Arts in Intercultural Studies (MAIS)",
            "filename": "3-mais-2024.pdf",
            "href": "/api/degree-plans/file/2024/3-mais-2024.pdf"
          },
          {
            "title": "Master of Arts in Intercultural Studies (MAIS) – pending",
            "filename": "3-mais-2024-pending.pdf",
            "href": "/api/degree-plans/file/2024/3-mais-2024-pending.pdf"
          },
          {
            "title": "Master of Arts in Spiritual Direction (MASD)",
            "filename": "3-masd-2024.pdf",
            "href": "/api/degree-plans/file/2024/3-masd-2024.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Aesthetics and Applied Arts",
            "filename": "3-mats-aesthetics-and-applied-arts2024.pdf",
            "href": "/api/degree-plans/file/2024/3-mats-aesthetics-and-applied-arts2024.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Anglican Studies",
            "filename": "3-mats-anglican-studies2024.pdf",
            "href": "/api/degree-plans/file/2024/3-mats-anglican-studies2024.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Ethics and Social",
            "filename": "3-mats-ethics-and-social2024.pdf",
            "href": "/api/degree-plans/file/2024/3-mats-ethics-and-social2024.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Philosophy & Apologetics",
            "filename": "3-mats-philosophy-apologetics2024.pdf",
            "href": "/api/degree-plans/file/2024/3-mats-philosophy-apologetics2024.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Spiritual Formation",
            "filename": "3-mats-spiritual-formation2024.pdf",
            "href": "/api/degree-plans/file/2024/3-mats-spiritual-formation2024.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Theology and History",
            "filename": "3-mats-theology-and-history2024.pdf",
            "href": "/api/degree-plans/file/2024/3-mats-theology-and-history2024.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Theology and Wesleyan",
            "filename": "3-mats-theology-and-wesleyan2024.pdf",
            "href": "/api/degree-plans/file/2024/3-mats-theology-and-wesleyan2024.pdf"
          }
        ]
      },
      {
        "id": "professional-ma",
        "title": "Professional Master’s",
        "links": [
          {
            "title": "Master of Arts in Christian Ministries (MACM)",
            "filename": "4-macm-2024.pdf",
            "href": "/api/degree-plans/file/2024/4-macm-2024.pdf"
          },
          {
            "title": "Master of Arts in Leadership (MAL) – No Track",
            "filename": "4-mal-no-track-2024.pdf",
            "href": "/api/degree-plans/file/2024/4-mal-no-track-2024.pdf"
          },
          {
            "title": "Master of Arts in Leadership (MAL) – Organizational Leadership Track",
            "filename": "4-mal-organizational-leadership-track-2024.pdf",
            "href": "/api/degree-plans/file/2024/4-mal-organizational-leadership-track-2024.pdf"
          },
          {
            "title": "Master of Arts in Leadership (MAL) – Social Impact",
            "filename": "4-mal-social-impact-2024.pdf",
            "href": "/api/degree-plans/file/2024/4-mal-social-impact-2024.pdf"
          },
          {
            "title": "Master of Arts in Leadership (MAL) – Worship Leadership",
            "filename": "4-mal-worship-leadership-2024.pdf",
            "href": "/api/degree-plans/file/2024/4-mal-worship-leadership-2024.pdf"
          },
          {
            "title": "Master of Arts in Marriage and Family Counseling (MAMF)",
            "filename": "4-mamf-2024.pdf",
            "href": "/api/degree-plans/file/2024/4-mamf-2024.pdf"
          },
          {
            "title": "Master of Arts in Mental Health Counseling (MAMH)",
            "filename": "4-mamh-2024.pdf",
            "href": "/api/degree-plans/file/2024/4-mamh-2024.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Children & Family Ministry",
            "filename": "4-mam-children-family-ministry-2024.pdf",
            "href": "/api/degree-plans/file/2024/4-mam-children-family-ministry-2024.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Church Planting",
            "filename": "4-mam-church-planting-2024.pdf",
            "href": "/api/degree-plans/file/2024/4-mam-church-planting-2024.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Congregational Leadership",
            "filename": "4-mam-congregational-leadership-2024.pdf",
            "href": "/api/degree-plans/file/2024/4-mam-congregational-leadership-2024.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Latino Ministry and Leadership",
            "filename": "4-mam-latino-ministry-and-leadership-2024.pdf",
            "href": "/api/degree-plans/file/2024/4-mam-latino-ministry-and-leadership-2024.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – No Track",
            "filename": "4-mam-no-track-2024.pdf",
            "href": "/api/degree-plans/file/2024/4-mam-no-track-2024.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Pastoral Care",
            "filename": "4-mam-pastoral-care-2024.pdf",
            "href": "/api/degree-plans/file/2024/4-mam-pastoral-care-2024.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Preaching",
            "filename": "4-mam-preaching-2024.pdf",
            "href": "/api/degree-plans/file/2024/4-mam-preaching-2024.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Worship",
            "filename": "4-mam-worship-2024.pdf",
            "href": "/api/degree-plans/file/2024/4-mam-worship-2024.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Youth & Family Ministry",
            "filename": "4-mam-youth-family-ministry-2024.pdf",
            "href": "/api/degree-plans/file/2024/4-mam-youth-family-ministry-2024.pdf"
          },
          {
            "title": "Master of Arts in Pastoral Counseling (MAPC) – Chaplaincy",
            "filename": "4-mapc-2024-chaplaincy.pdf",
            "href": "/api/degree-plans/file/2024/4-mapc-2024-chaplaincy.pdf"
          },
          {
            "title": "Master of Arts in Pastoral Counseling (MAPC) – Marriage & Family Pastoral Counselor",
            "filename": "4-mapc-2024-marriage-family-pastoral-counselor.pdf",
            "href": "/api/degree-plans/file/2024/4-mapc-2024-marriage-family-pastoral-counselor.pdf"
          },
          {
            "title": "Master of Arts in Pastoral Counseling (MAPC) – No Track",
            "filename": "4-mapc-2024-no-track.pdf",
            "href": "/api/degree-plans/file/2024/4-mapc-2024-no-track.pdf"
          },
          {
            "title": "Master of Arts in Pastoral Studies (MAPS)",
            "filename": "4-maps-2024.pdf",
            "href": "/api/degree-plans/file/2024/4-maps-2024.pdf"
          }
        ]
      },
      {
        "id": "doctoral",
        "title": "Doctoral / Advanced",
        "links": [
          {
            "title": "Doctor of Ministry (DMin)",
            "filename": "5-dmin-2024.pdf",
            "href": "/api/degree-plans/file/2024/5-dmin-2024.pdf"
          },
          {
            "title": "Doctor of Philosophy in Biblical Studies (PhD)",
            "filename": "5-phd-bs-2024.pdf",
            "href": "/api/degree-plans/file/2024/5-phd-bs-2024.pdf"
          },
          {
            "title": "Doctor of Philosophy in Intercultural Studies (PhD)",
            "filename": "5-phd-is-2024.pdf",
            "href": "/api/degree-plans/file/2024/5-phd-is-2024.pdf"
          },
          {
            "title": "Master of Theology in Biblical Studies (ThM)",
            "filename": "5-thm-bs-2024.pdf",
            "href": "/api/degree-plans/file/2024/5-thm-bs-2024.pdf"
          },
          {
            "title": "Master of Theology in Intercultural Studies (ThM)",
            "filename": "5-thm-is-2024.pdf",
            "href": "/api/degree-plans/file/2024/5-thm-is-2024.pdf"
          },
          {
            "title": "Master of Theology in Theological Studies (ThM)",
            "filename": "5-thm-ts-2024.pdf",
            "href": "/api/degree-plans/file/2024/5-thm-ts-2024.pdf"
          }
        ]
      },
      {
        "id": "other",
        "title": "Other",
        "links": [
          {
            "title": "Master of Biblical and Theological Foundations (MBTF)",
            "filename": "mbtf-2024.pdf",
            "href": "/api/degree-plans/file/2024/mbtf-2024.pdf"
          }
        ]
      }
    ]
  },
  {
    "year": 2023,
    "sections": [
      {
        "id": "cert",
        "title": "Certificate Programs",
        "links": [
          {
            "title": "Certificate in (CS - Christian Studies)2022",
            "filename": "1-cert-cs-christian-studies2022.pdf",
            "href": "/api/degree-plans/file/2023/1-cert-cs-christian-studies2022.pdf"
          },
          {
            "title": "Certificate in Anglican Studies",
            "filename": "1-cert-as-anglican-studies2023.pdf",
            "href": "/api/degree-plans/file/2023/1-cert-as-anglican-studies2023.pdf"
          },
          {
            "title": "Certificate in Christian Discipleship",
            "filename": "1-cert-cd-christian-discipleship2023.pdf",
            "href": "/api/degree-plans/file/2023/1-cert-cd-christian-discipleship2023.pdf"
          },
          {
            "title": "Certificate in Christian Education",
            "filename": "1-cert-ce-christian-education2023.pdf",
            "href": "/api/degree-plans/file/2023/1-cert-ce-christian-education2023.pdf"
          },
          {
            "title": "Certificate in Hispanic Min Formation",
            "filename": "1-cert-hm-hispanic-min-formation2023.pdf",
            "href": "/api/degree-plans/file/2023/1-cert-hm-hispanic-min-formation2023.pdf"
          },
          {
            "title": "Certificate in Intercultural Studies",
            "filename": "1-cert-is-intercultural-studies2023.pdf",
            "href": "/api/degree-plans/file/2023/1-cert-is-intercultural-studies2023.pdf"
          },
          {
            "title": "Certificate in Leadership",
            "filename": "1-cert-ld-leadership2023.pdf",
            "href": "/api/degree-plans/file/2023/1-cert-ld-leadership2023.pdf"
          },
          {
            "title": "Certificate in Ministry Level 1",
            "filename": "1-cert-m1-ministry-level-12023.pdf",
            "href": "/api/degree-plans/file/2023/1-cert-m1-ministry-level-12023.pdf"
          },
          {
            "title": "Certificate in Missional Discipleship",
            "filename": "1-cert-md-missional-discipleship2023.pdf",
            "href": "/api/degree-plans/file/2023/1-cert-md-missional-discipleship2023.pdf"
          },
          {
            "title": "Certificate in Pastoral Care",
            "filename": "1-cert-pc-pastoral-care2023.pdf",
            "href": "/api/degree-plans/file/2023/1-cert-pc-pastoral-care2023.pdf"
          },
          {
            "title": "Certificate in Youth and Family",
            "filename": "1-cert-ym-youth-and-family2023.pdf",
            "href": "/api/degree-plans/file/2023/1-cert-ym-youth-and-family2023.pdf"
          }
        ]
      },
      {
        "id": "mdiv",
        "title": "Master of Divinity",
        "links": [
          {
            "title": "Master of Divinity (MDiv) – Aesthetics and Applied Arts",
            "filename": "2-mdiv-2023-aesthics-and-applied-arts-concentration.pdf",
            "href": "/api/degree-plans/file/2023/2-mdiv-2023-aesthics-and-applied-arts-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Anglican Studies",
            "filename": "2-mdiv-2023-anglican-studies-concentration.pdf",
            "href": "/api/degree-plans/file/2023/2-mdiv-2023-anglican-studies-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Biblical Studies",
            "filename": "2-mdiv-2023-biblical-studies-concentration.pdf",
            "href": "/api/degree-plans/file/2023/2-mdiv-2023-biblical-studies-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Chaplaincy",
            "filename": "2-mdiv-2023-chaplaincy-concentration.pdf",
            "href": "/api/degree-plans/file/2023/2-mdiv-2023-chaplaincy-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Christian Discipleship",
            "filename": "2-mdiv-2023-christian-discipleship-concentration.pdf",
            "href": "/api/degree-plans/file/2023/2-mdiv-2023-christian-discipleship-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Christian Leadership",
            "filename": "2-mdiv-2023-christian-leadership-concentration.pdf",
            "href": "/api/degree-plans/file/2023/2-mdiv-2023-christian-leadership-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Church Planting",
            "filename": "2-mdiv-2023-church-planting-concentration.pdf",
            "href": "/api/degree-plans/file/2023/2-mdiv-2023-church-planting-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Ethics and Social Responsibility",
            "filename": "2-mdiv-2023-ethics-and-social-responsibility-concentration.pdf",
            "href": "/api/degree-plans/file/2023/2-mdiv-2023-ethics-and-social-responsibility-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Intercultural Studies",
            "filename": "2-mdiv-2023-intercultural-studies-concentration.pdf",
            "href": "/api/degree-plans/file/2023/2-mdiv-2023-intercultural-studies-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – No Concentrations",
            "filename": "2-mdiv-2023-no-concentrations.pdf",
            "href": "/api/degree-plans/file/2023/2-mdiv-2023-no-concentrations.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Pastoral Counseling",
            "filename": "2-mdiv-2023-pastoral-counseling-concentration.pdf",
            "href": "/api/degree-plans/file/2023/2-mdiv-2023-pastoral-counseling-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Spiritual Formation",
            "filename": "2-mdiv-2023-spiritual-formation-concentration.pdf",
            "href": "/api/degree-plans/file/2023/2-mdiv-2023-spiritual-formation-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Theological Studies",
            "filename": "2-mdiv-2023-theological-studies.pdf",
            "href": "/api/degree-plans/file/2023/2-mdiv-2023-theological-studies.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Theology and Wesleyan Studies",
            "filename": "2-mdiv-2023-theology-and-wesleyan-studies.pdf",
            "href": "/api/degree-plans/file/2023/2-mdiv-2023-theology-and-wesleyan-studies.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Youth Ministry",
            "filename": "2-mdiv-2023-youth-ministry-concentration.pdf",
            "href": "/api/degree-plans/file/2023/2-mdiv-2023-youth-ministry-concentration.pdf"
          }
        ]
      },
      {
        "id": "academic-ma",
        "title": "Academic Master’s",
        "links": [
          {
            "title": "Master of Arts in Biblical Studies (MABS)",
            "filename": "3-mabs-2023.pdf",
            "href": "/api/degree-plans/file/2023/3-mabs-2023.pdf"
          },
          {
            "title": "Master of Arts in Intercultural Studies (MAIS)",
            "filename": "3-mais-2023.pdf",
            "href": "/api/degree-plans/file/2023/3-mais-2023.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Aesthetics and Applied Arts",
            "filename": "3-mats-aesthetics-and-applied-arts2023.pdf",
            "href": "/api/degree-plans/file/2023/3-mats-aesthetics-and-applied-arts2023.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Anglican Studies",
            "filename": "3-mats-anglican-studies2023.pdf",
            "href": "/api/degree-plans/file/2023/3-mats-anglican-studies2023.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Ethics and Social",
            "filename": "3-mats-ethics-and-social2023.pdf",
            "href": "/api/degree-plans/file/2023/3-mats-ethics-and-social2023.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Philosophy & Apologetics",
            "filename": "3-mats-philosophy-apologetics2023.pdf",
            "href": "/api/degree-plans/file/2023/3-mats-philosophy-apologetics2023.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Spiritual Formation",
            "filename": "3-mats-spiritual-formation2023.pdf",
            "href": "/api/degree-plans/file/2023/3-mats-spiritual-formation2023.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Theology and History",
            "filename": "3-mats-theology-and-history2023.pdf",
            "href": "/api/degree-plans/file/2023/3-mats-theology-and-history2023.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Theology and Wesleyan",
            "filename": "3-mats-theology-and-wesleyan2023.pdf",
            "href": "/api/degree-plans/file/2023/3-mats-theology-and-wesleyan2023.pdf"
          }
        ]
      },
      {
        "id": "professional-ma",
        "title": "Professional Master’s",
        "links": [
          {
            "title": "Master of Arts in Christian Ministries (MACM)",
            "filename": "4-macm-2023.pdf",
            "href": "/api/degree-plans/file/2023/4-macm-2023.pdf"
          },
          {
            "title": "Master of Arts in Leadership (MAL) – No Concentration",
            "filename": "4-mal-no-concentration-2023.pdf",
            "href": "/api/degree-plans/file/2023/4-mal-no-concentration-2023.pdf"
          },
          {
            "title": "Master of Arts in Leadership (MAL) – Organizational Leadership Track",
            "filename": "4-mal-organizational-leadership-track-2023.pdf",
            "href": "/api/degree-plans/file/2023/4-mal-organizational-leadership-track-2023.pdf"
          },
          {
            "title": "Master of Arts in Leadership (MAL) – Social Impact",
            "filename": "4-mal-social-impact-2023.pdf",
            "href": "/api/degree-plans/file/2023/4-mal-social-impact-2023.pdf"
          },
          {
            "title": "Master of Arts in Leadership (MAL) – Worship Leadership",
            "filename": "4-mal-worship-leadership-2023.pdf",
            "href": "/api/degree-plans/file/2023/4-mal-worship-leadership-2023.pdf"
          },
          {
            "title": "Master of Arts in Marriage and Family Counseling (MAMF)",
            "filename": "4-mamf-2023.pdf",
            "href": "/api/degree-plans/file/2023/4-mamf-2023.pdf"
          },
          {
            "title": "Master of Arts in Mental Health Counseling (MAMH)",
            "filename": "4-mamh-2023.pdf",
            "href": "/api/degree-plans/file/2023/4-mamh-2023.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Children & Family Ministry Concentration",
            "filename": "4-mam-children-family-ministry-concentration-2023.pdf",
            "href": "/api/degree-plans/file/2023/4-mam-children-family-ministry-concentration-2023.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Church Planting Concentration",
            "filename": "4-mam-church-planting-concentration-2023.pdf",
            "href": "/api/degree-plans/file/2023/4-mam-church-planting-concentration-2023.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Congregational Leadership Concentration",
            "filename": "4-mam-congregational-leadership-concentration-2023.pdf",
            "href": "/api/degree-plans/file/2023/4-mam-congregational-leadership-concentration-2023.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Latino Ministry and Leadership Concentration",
            "filename": "4-mam-latino-ministry-and-leadership-concentration-2023.pdf",
            "href": "/api/degree-plans/file/2023/4-mam-latino-ministry-and-leadership-concentration-2023.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – No Concentration",
            "filename": "4-mam-no-concentration-2023.pdf",
            "href": "/api/degree-plans/file/2023/4-mam-no-concentration-2023.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Pastoral Care Concentration",
            "filename": "4-mam-pastoral-care-concentration-2023.pdf",
            "href": "/api/degree-plans/file/2023/4-mam-pastoral-care-concentration-2023.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Preaching Concentration",
            "filename": "4-mam-preaching-concentration-2023.pdf",
            "href": "/api/degree-plans/file/2023/4-mam-preaching-concentration-2023.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – With Concentration",
            "filename": "4-mam-with-concentration-2023.pdf",
            "href": "/api/degree-plans/file/2023/4-mam-with-concentration-2023.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Worship Concentration",
            "filename": "4-mam-worship-concentration-2023.pdf",
            "href": "/api/degree-plans/file/2023/4-mam-worship-concentration-2023.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Youth & Family Ministry Concentration",
            "filename": "4-mam-youth-family-ministry-concentration-2023.pdf",
            "href": "/api/degree-plans/file/2023/4-mam-youth-family-ministry-concentration-2023.pdf"
          },
          {
            "title": "Master of Arts in Pastoral Counseling (MAPC)",
            "filename": "4-mapc-2023.pdf",
            "href": "/api/degree-plans/file/2023/4-mapc-2023.pdf"
          }
        ]
      },
      {
        "id": "doctoral",
        "title": "Doctoral / Advanced",
        "links": [
          {
            "title": "Doctor of Ministry (DMin)",
            "filename": "5-dmin-2023.pdf",
            "href": "/api/degree-plans/file/2023/5-dmin-2023.pdf"
          },
          {
            "title": "Doctor of Philosophy in Biblical Studies (PhD)",
            "filename": "5-phd-bs-2023.pdf",
            "href": "/api/degree-plans/file/2023/5-phd-bs-2023.pdf"
          },
          {
            "title": "Doctor of Philosophy in Intercultural Studies (PhD)",
            "filename": "5-phd-is-2023.pdf",
            "href": "/api/degree-plans/file/2023/5-phd-is-2023.pdf"
          },
          {
            "title": "Master of Theology in Biblical Studies (ThM)",
            "filename": "5-thm-bs-2023.pdf",
            "href": "/api/degree-plans/file/2023/5-thm-bs-2023.pdf"
          },
          {
            "title": "Master of Theology in Intercultural Studies (ThM)",
            "filename": "5-thm-is-2023.pdf",
            "href": "/api/degree-plans/file/2023/5-thm-is-2023.pdf"
          },
          {
            "title": "Master of Theology in Theological Studies (ThM)",
            "filename": "5-thm-ts-2023.pdf",
            "href": "/api/degree-plans/file/2023/5-thm-ts-2023.pdf"
          }
        ]
      },
      {
        "id": "other",
        "title": "Other",
        "links": [
          {
            "title": "Master of Biblical and Theological Foundations (MBTF)",
            "filename": "mbtf-2023.pdf",
            "href": "/api/degree-plans/file/2023/mbtf-2023.pdf"
          }
        ]
      }
    ]
  },
  {
    "year": 2022,
    "sections": [
      {
        "id": "cert",
        "title": "Certificate Programs",
        "links": [
          {
            "title": "Certificate in Anglican Studies",
            "filename": "1-cert-as-anglican-studies2022.pdf",
            "href": "/api/degree-plans/file/2022/1-cert-as-anglican-studies2022.pdf"
          },
          {
            "title": "Certificate in Christian Discipleship",
            "filename": "1-cert-ce-christian-discipleship2022.pdf",
            "href": "/api/degree-plans/file/2022/1-cert-ce-christian-discipleship2022.pdf"
          },
          {
            "title": "Certificate in Christian Education",
            "filename": "1-cert-ce-christian-education2022.pdf",
            "href": "/api/degree-plans/file/2022/1-cert-ce-christian-education2022.pdf"
          },
          {
            "title": "Certificate in Christian Studies",
            "filename": "1-cert-cs-christian-studies2022.pdf",
            "href": "/api/degree-plans/file/2022/1-cert-cs-christian-studies2022.pdf"
          },
          {
            "title": "Certificate in Hispanic Min Formation",
            "filename": "1-cert-hm-hispanic-min-formation2022.pdf",
            "href": "/api/degree-plans/file/2022/1-cert-hm-hispanic-min-formation2022.pdf"
          },
          {
            "title": "Certificate in Intercultural Studies",
            "filename": "1-cert-is-intercultural-studies2022.pdf",
            "href": "/api/degree-plans/file/2022/1-cert-is-intercultural-studies2022.pdf"
          },
          {
            "title": "Certificate in Leadership Dev",
            "filename": "1-cert-ld-leadership-dev2022.pdf",
            "href": "/api/degree-plans/file/2022/1-cert-ld-leadership-dev2022.pdf"
          },
          {
            "title": "Certificate in Ministry Level 1",
            "filename": "1-cert-m1-ministry-level-12022.pdf",
            "href": "/api/degree-plans/file/2022/1-cert-m1-ministry-level-12022.pdf"
          },
          {
            "title": "Certificate in Missional Discipleship",
            "filename": "1-cert-md-missional-discipleship2022.pdf",
            "href": "/api/degree-plans/file/2022/1-cert-md-missional-discipleship2022.pdf"
          },
          {
            "title": "Certificate in Pastoral Care",
            "filename": "1-cert-pc-pastoral-care2022.pdf",
            "href": "/api/degree-plans/file/2022/1-cert-pc-pastoral-care2022.pdf"
          },
          {
            "title": "Certificate in Youth and Family",
            "filename": "1-cert-ym-youth-and-family2022.pdf",
            "href": "/api/degree-plans/file/2022/1-cert-ym-youth-and-family2022.pdf"
          }
        ]
      },
      {
        "id": "mdiv",
        "title": "Master of Divinity",
        "links": [
          {
            "title": "Master of Divinity (MDiv) – Aesthetics and Applied Arts",
            "filename": "2-mdiv-2022-aesthics-and-applied-arts-concentration.pdf",
            "href": "/api/degree-plans/file/2022/2-mdiv-2022-aesthics-and-applied-arts-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Anglican Studies",
            "filename": "2-mdiv-2022-anglican-studies-concentration.pdf",
            "href": "/api/degree-plans/file/2022/2-mdiv-2022-anglican-studies-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Biblical Studies",
            "filename": "2-mdiv-2022-biblical-studies-concentration.pdf",
            "href": "/api/degree-plans/file/2022/2-mdiv-2022-biblical-studies-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Chaplaincy",
            "filename": "2-mdiv-2022-chaplaincy-concentration.pdf",
            "href": "/api/degree-plans/file/2022/2-mdiv-2022-chaplaincy-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Christian Discipleship",
            "filename": "2-mdiv-2022-christian-discipleship-concentration.pdf",
            "href": "/api/degree-plans/file/2022/2-mdiv-2022-christian-discipleship-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Christian Leadership",
            "filename": "2-mdiv-2022-christian-leadership-concentration.pdf",
            "href": "/api/degree-plans/file/2022/2-mdiv-2022-christian-leadership-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Church Planting",
            "filename": "2-mdiv-2022-church-planting-concentration.pdf",
            "href": "/api/degree-plans/file/2022/2-mdiv-2022-church-planting-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Ethics and Social Responsibility",
            "filename": "2-mdiv-2022-ethics-and-social-responsibility-concentration.pdf",
            "href": "/api/degree-plans/file/2022/2-mdiv-2022-ethics-and-social-responsibility-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Intercultural Studies",
            "filename": "2-mdiv-2022-intercultural-studies-concentration.pdf",
            "href": "/api/degree-plans/file/2022/2-mdiv-2022-intercultural-studies-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – No Concentrations",
            "filename": "2-mdiv-2022-no-concentrations.pdf",
            "href": "/api/degree-plans/file/2022/2-mdiv-2022-no-concentrations.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Pastoral Counseling",
            "filename": "2-mdiv-2022-pastoral-counseling-concentration.pdf",
            "href": "/api/degree-plans/file/2022/2-mdiv-2022-pastoral-counseling-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Spiritual Formation",
            "filename": "2-mdiv-2022-spiritual-formation-concentration.pdf",
            "href": "/api/degree-plans/file/2022/2-mdiv-2022-spiritual-formation-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Theological Studies",
            "filename": "2-mdiv-2022-theological-studies.pdf",
            "href": "/api/degree-plans/file/2022/2-mdiv-2022-theological-studies.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Theology and Wesleyan Studies",
            "filename": "2-mdiv-2022-theology-and-wesleyan-studies.pdf",
            "href": "/api/degree-plans/file/2022/2-mdiv-2022-theology-and-wesleyan-studies.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Youth Ministry",
            "filename": "2-mdiv-2022-youth-ministry-concentration.pdf",
            "href": "/api/degree-plans/file/2022/2-mdiv-2022-youth-ministry-concentration.pdf"
          }
        ]
      },
      {
        "id": "academic-ma",
        "title": "Academic Master’s",
        "links": [
          {
            "title": "Master of Arts in Biblical Studies (MABS)",
            "filename": "3-mabs-2022.pdf",
            "href": "/api/degree-plans/file/2022/3-mabs-2022.pdf"
          },
          {
            "title": "Master of Arts in Intercultural Studies (MAIS)",
            "filename": "3-mais-2022.pdf",
            "href": "/api/degree-plans/file/2022/3-mais-2022.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Aesthetics and Applied Arts",
            "filename": "3-mats-aesthetics-and-applied-arts2022.pdf",
            "href": "/api/degree-plans/file/2022/3-mats-aesthetics-and-applied-arts2022.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Anglican Studies",
            "filename": "3-mats-anglican-studies2022.pdf",
            "href": "/api/degree-plans/file/2022/3-mats-anglican-studies2022.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Ethics and Social",
            "filename": "3-mats-ethics-and-social2022.pdf",
            "href": "/api/degree-plans/file/2022/3-mats-ethics-and-social2022.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Philosophy & Apologetics",
            "filename": "3-mats-philosophy-apologetics2022.pdf",
            "href": "/api/degree-plans/file/2022/3-mats-philosophy-apologetics2022.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Spiritual Formation",
            "filename": "3-mats-spiritual-formation2022.pdf",
            "href": "/api/degree-plans/file/2022/3-mats-spiritual-formation2022.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Theology and History",
            "filename": "3-mats-theology-and-history2022.pdf",
            "href": "/api/degree-plans/file/2022/3-mats-theology-and-history2022.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Theology and Wesleyan",
            "filename": "3-mats-theology-and-wesleyan2022.pdf",
            "href": "/api/degree-plans/file/2022/3-mats-theology-and-wesleyan2022.pdf"
          }
        ]
      },
      {
        "id": "professional-ma",
        "title": "Professional Master’s",
        "links": [
          {
            "title": "Master of Arts in Christian Ministries (MACM)",
            "filename": "4-macm-2022.pdf",
            "href": "/api/degree-plans/file/2022/4-macm-2022.pdf"
          },
          {
            "title": "Master of Arts in Leadership (MAL) – No Concentration",
            "filename": "4-mal-no-concentration-2022.pdf",
            "href": "/api/degree-plans/file/2022/4-mal-no-concentration-2022.pdf"
          },
          {
            "title": "Master of Arts in Leadership (MAL) – Organizational Leadership Track",
            "filename": "4-mal-organizational-leadership-track-2022.pdf",
            "href": "/api/degree-plans/file/2022/4-mal-organizational-leadership-track-2022.pdf"
          },
          {
            "title": "Master of Arts in Leadership (MAL) – Social Impact",
            "filename": "4-mal-social-impact-2022.pdf",
            "href": "/api/degree-plans/file/2022/4-mal-social-impact-2022.pdf"
          },
          {
            "title": "Master of Arts in Leadership (MAL) – Worship Leadership",
            "filename": "4-mal-worship-leadership-2022.pdf",
            "href": "/api/degree-plans/file/2022/4-mal-worship-leadership-2022.pdf"
          },
          {
            "title": "Master of Arts in Marriage and Family Counseling (MAMF)",
            "filename": "4-mamf-2022.pdf",
            "href": "/api/degree-plans/file/2022/4-mamf-2022.pdf"
          },
          {
            "title": "Master of Arts in Mental Health Counseling (MAMH)",
            "filename": "4-mamh-2022.pdf",
            "href": "/api/degree-plans/file/2022/4-mamh-2022.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Church Planting Concentration",
            "filename": "4-mam-church-planting-concentration-2022.pdf",
            "href": "/api/degree-plans/file/2022/4-mam-church-planting-concentration-2022.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Latino Ministry and Leadership Concentration",
            "filename": "4-mam-latino-ministry-and-leadership-concentration-2022.pdf",
            "href": "/api/degree-plans/file/2022/4-mam-latino-ministry-and-leadership-concentration-2022.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – No Concentration",
            "filename": "4-mam-no-concentration-2022.pdf",
            "href": "/api/degree-plans/file/2022/4-mam-no-concentration-2022.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – With Concentration",
            "filename": "4-mam-with-concentration-2022.pdf",
            "href": "/api/degree-plans/file/2022/4-mam-with-concentration-2022.pdf"
          },
          {
            "title": "Master of Arts in Pastoral Counseling (MAPC)",
            "filename": "4-mapc-2022.pdf",
            "href": "/api/degree-plans/file/2022/4-mapc-2022.pdf"
          }
        ]
      },
      {
        "id": "doctoral",
        "title": "Doctoral / Advanced",
        "links": [
          {
            "title": "Doctor of Ministry (DMin)",
            "filename": "5-dmin-2022.pdf",
            "href": "/api/degree-plans/file/2022/5-dmin-2022.pdf"
          },
          {
            "title": "Doctor of Philosophy in Biblical Studies (PhD)",
            "filename": "5-phd-bs-2022.pdf",
            "href": "/api/degree-plans/file/2022/5-phd-bs-2022.pdf"
          },
          {
            "title": "Doctor of Philosophy in Intercultural Studies (PhD)",
            "filename": "5-phd-is-2022.pdf",
            "href": "/api/degree-plans/file/2022/5-phd-is-2022.pdf"
          },
          {
            "title": "Master of Theology in Biblical Studies (ThM)",
            "filename": "5-thm-bs-2022.pdf",
            "href": "/api/degree-plans/file/2022/5-thm-bs-2022.pdf"
          },
          {
            "title": "Master of Theology in Intercultural Studies (ThM)",
            "filename": "5-thm-is-2022.pdf",
            "href": "/api/degree-plans/file/2022/5-thm-is-2022.pdf"
          },
          {
            "title": "Master of Theology in Theological Studies (ThM)",
            "filename": "5-thm-ts-2022.pdf",
            "href": "/api/degree-plans/file/2022/5-thm-ts-2022.pdf"
          },
          {
            "title": "Master of Theology in Theological Studies (ThM) – 2",
            "filename": "5-thm-ts-20222.pdf",
            "href": "/api/degree-plans/file/2022/5-thm-ts-20222.pdf"
          }
        ]
      },
      {
        "id": "other",
        "title": "Other",
        "links": [
          {
            "title": "Master of Biblical and Theological Foundations (MBTF)",
            "filename": "mbtf-2022.pdf",
            "href": "/api/degree-plans/file/2022/mbtf-2022.pdf"
          }
        ]
      }
    ]
  },
  {
    "year": 2021,
    "sections": [
      {
        "id": "academic-ma",
        "title": "Academic Master’s",
        "links": [
          {
            "title": "Master of Arts in Theological Studies (MATS) – Theology and History",
            "filename": "3-mats-theology-and-history2021.pdf",
            "href": "/api/degree-plans/file/2021/3-mats-theology-and-history2021.pdf"
          }
        ]
      },
      {
        "id": "professional-ma",
        "title": "Professional Master’s",
        "links": [
          {
            "title": "Master of Arts in Marriage and Family Counseling (MAMF)",
            "filename": "4-mamf-2021.pdf",
            "href": "/api/degree-plans/file/2021/4-mamf-2021.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Latino Ministry & Leadership Concentration",
            "filename": "4-mam-latino-ministry-leadership-concentration-2021.pdf",
            "href": "/api/degree-plans/file/2021/4-mam-latino-ministry-leadership-concentration-2021.pdf"
          },
          {
            "title": "Master of Arts in Pastoral Counseling (MAPC)",
            "filename": "4-mapc-2021.pdf",
            "href": "/api/degree-plans/file/2021/4-mapc-2021.pdf"
          }
        ]
      },
      {
        "id": "other",
        "title": "Other",
        "links": [
          {
            "title": "Master of Biblical and Theological Foundations (MBTF)",
            "filename": "mbtf-2021.pdf",
            "href": "/api/degree-plans/file/2021/mbtf-2021.pdf"
          }
        ]
      }
    ]
  },
  {
    "year": 2020,
    "sections": [
      {
        "id": "cert",
        "title": "Certificate Programs",
        "links": [
          {
            "title": "Certificate in Aging & Spirituality",
            "filename": "1-cert-as-aging-spirituality-2020.pdf",
            "href": "/api/degree-plans/file/2020/1-cert-as-aging-spirituality-2020.pdf"
          },
          {
            "title": "Certificate in Anglican Studies",
            "filename": "1-cert-as-anglican-studies-2020.pdf",
            "href": "/api/degree-plans/file/2020/1-cert-as-anglican-studies-2020.pdf"
          },
          {
            "title": "Certificate in Christian Discipleship",
            "filename": "1-cert-cd-christian-discipleship-2020.pdf",
            "href": "/api/degree-plans/file/2020/1-cert-cd-christian-discipleship-2020.pdf"
          },
          {
            "title": "Certificate in Christian Education",
            "filename": "1-cert-ce-christian-education-2020.pdf",
            "href": "/api/degree-plans/file/2020/1-cert-ce-christian-education-2020.pdf"
          },
          {
            "title": "Certificate in Christian Studies",
            "filename": "1-cert-cs-christian-studies-2020.pdf",
            "href": "/api/degree-plans/file/2020/1-cert-cs-christian-studies-2020.pdf"
          },
          {
            "title": "Certificate in Hispanic Ministry Formation",
            "filename": "1-cert-hmf-hispanic-ministry-formation-2020.pdf",
            "href": "/api/degree-plans/file/2020/1-cert-hmf-hispanic-ministry-formation-2020.pdf"
          },
          {
            "title": "Certificate in Intercultural Studies",
            "filename": "1-cert-is-intercultural-studies-2020.pdf",
            "href": "/api/degree-plans/file/2020/1-cert-is-intercultural-studies-2020.pdf"
          },
          {
            "title": "Certificate in Leadership Dev",
            "filename": "1-cert-ld-leadership-dev-2020.pdf",
            "href": "/api/degree-plans/file/2020/1-cert-ld-leadership-dev-2020.pdf"
          },
          {
            "title": "Certificate in Pastoral Care",
            "filename": "1-cert-pc-pastoral-care-2020.pdf",
            "href": "/api/degree-plans/file/2020/1-cert-pc-pastoral-care-2020.pdf"
          },
          {
            "title": "Certificate in Youth and Family Ministries",
            "filename": "1-cert-yfm-youth-and-family-ministries-2020.pdf",
            "href": "/api/degree-plans/file/2020/1-cert-yfm-youth-and-family-ministries-2020.pdf"
          }
        ]
      },
      {
        "id": "mdiv",
        "title": "Master of Divinity",
        "links": [
          {
            "title": "Master of Divinity (MDiv) – Aging and Spirituality",
            "filename": "2-mdiv-2020-aging-and-spirituality-concentration.pdf",
            "href": "/api/degree-plans/file/2020/2-mdiv-2020-aging-and-spirituality-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Anglican Studies",
            "filename": "2-mdiv-2020-anglican-studies-concentration.pdf",
            "href": "/api/degree-plans/file/2020/2-mdiv-2020-anglican-studies-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Biblical Studies",
            "filename": "2-mdiv-2020-biblical-studies-concentration.pdf",
            "href": "/api/degree-plans/file/2020/2-mdiv-2020-biblical-studies-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Christian Discipleship",
            "filename": "2-mdiv-2020-christian-discipleship-concentration.pdf",
            "href": "/api/degree-plans/file/2020/2-mdiv-2020-christian-discipleship-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Christian Leadership",
            "filename": "2-mdiv-2020-christian-leadership-concentration.pdf",
            "href": "/api/degree-plans/file/2020/2-mdiv-2020-christian-leadership-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Church Planting",
            "filename": "2-mdiv-2020-church-planting-concentration.pdf",
            "href": "/api/degree-plans/file/2020/2-mdiv-2020-church-planting-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Intercultural Studies",
            "filename": "2-mdiv-2020-intercultural-studies-concentration.pdf",
            "href": "/api/degree-plans/file/2020/2-mdiv-2020-intercultural-studies-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – No Concentrations",
            "filename": "2-mdiv-2020-no-concentrations.pdf",
            "href": "/api/degree-plans/file/2020/2-mdiv-2020-no-concentrations.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Pastoral Counseling",
            "filename": "2-mdiv-2020-pastoral-counseling-concentration.pdf",
            "href": "/api/degree-plans/file/2020/2-mdiv-2020-pastoral-counseling-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Spiritual Formation",
            "filename": "2-mdiv-2020-spiritual-formation-concentration.pdf",
            "href": "/api/degree-plans/file/2020/2-mdiv-2020-spiritual-formation-concentration.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Theological Studies",
            "filename": "2-mdiv-2020-theological-studies.pdf",
            "href": "/api/degree-plans/file/2020/2-mdiv-2020-theological-studies.pdf"
          },
          {
            "title": "Master of Divinity (MDiv) – Youth Ministry",
            "filename": "2-mdiv-2020-youth-ministry-concentration.pdf",
            "href": "/api/degree-plans/file/2020/2-mdiv-2020-youth-ministry-concentration.pdf"
          }
        ]
      },
      {
        "id": "academic-ma",
        "title": "Academic Master’s",
        "links": [
          {
            "title": "Master of Arts in Biblical Studies (MABS)",
            "filename": "3-mabs-2020.pdf",
            "href": "/api/degree-plans/file/2020/3-mabs-2020.pdf"
          },
          {
            "title": "Master of Arts in Intercultural Studies (MAIS)",
            "filename": "3-mais-2020.pdf",
            "href": "/api/degree-plans/file/2020/3-mais-2020.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Anglican Studies",
            "filename": "3-mats-anglican-studies-2020.pdf",
            "href": "/api/degree-plans/file/2020/3-mats-anglican-studies-2020.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Philosophy & Apologetics",
            "filename": "3-mats-philosophy-apologetics-2020.pdf",
            "href": "/api/degree-plans/file/2020/3-mats-philosophy-apologetics-2020.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Spiritual Formation",
            "filename": "3-mats-spiritual-formation-2020.pdf",
            "href": "/api/degree-plans/file/2020/3-mats-spiritual-formation-2020.pdf"
          },
          {
            "title": "Master of Arts in Theological Studies (MATS) – Theology and History",
            "filename": "3-mats-theology-and-history-2020.pdf",
            "href": "/api/degree-plans/file/2020/3-mats-theology-and-history-2020.pdf"
          }
        ]
      },
      {
        "id": "professional-ma",
        "title": "Professional Master’s",
        "links": [
          {
            "title": "Master of Arts in Christian Ministries (MACM)",
            "filename": "4-macm-2020.pdf",
            "href": "/api/degree-plans/file/2020/4-macm-2020.pdf"
          },
          {
            "title": "Master of Arts in Leadership (MAL) – No Concentration",
            "filename": "4-mal-no-concentration-2020.pdf",
            "href": "/api/degree-plans/file/2020/4-mal-no-concentration-2020.pdf"
          },
          {
            "title": "Master of Arts in Leadership (MAL) – Organizational Leadership Track",
            "filename": "4-mal-organizational-leadership-track-2020.pdf",
            "href": "/api/degree-plans/file/2020/4-mal-organizational-leadership-track-2020.pdf"
          },
          {
            "title": "Master of Arts in Leadership (MAL) – Social Impact",
            "filename": "4-mal-social-impact-2020.pdf",
            "href": "/api/degree-plans/file/2020/4-mal-social-impact-2020.pdf"
          },
          {
            "title": "Master of Arts in Leadership (MAL) – Worship Leadership",
            "filename": "4-mal-worship-leadership-2020.pdf",
            "href": "/api/degree-plans/file/2020/4-mal-worship-leadership-2020.pdf"
          },
          {
            "title": "Master of Arts in Marriage and Family Counseling (MAMF)",
            "filename": "4-mamf-2020.pdf",
            "href": "/api/degree-plans/file/2020/4-mamf-2020.pdf"
          },
          {
            "title": "Master of Arts in Mental Health Counseling (MAMH)",
            "filename": "4-mamh-2020.pdf",
            "href": "/api/degree-plans/file/2020/4-mamh-2020.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – Latino Ministries and Leadership",
            "filename": "4-mam-latino-ministries-and-leadership-2020.pdf",
            "href": "/api/degree-plans/file/2020/4-mam-latino-ministries-and-leadership-2020.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – No Concentration",
            "filename": "4-mam-no-concentration-2020.pdf",
            "href": "/api/degree-plans/file/2020/4-mam-no-concentration-2020.pdf"
          },
          {
            "title": "Master of Arts in Ministry (MAM) – With Concentration",
            "filename": "4-mam-with-concentration-2020.pdf",
            "href": "/api/degree-plans/file/2020/4-mam-with-concentration-2020.pdf"
          },
          {
            "title": "Master of Arts in Pastoral Counseling (MAPC)",
            "filename": "4-mapc-2020.pdf",
            "href": "/api/degree-plans/file/2020/4-mapc-2020.pdf"
          }
        ]
      },
      {
        "id": "doctoral",
        "title": "Doctoral / Advanced",
        "links": [
          {
            "title": "Doctor of Ministry (DMin)",
            "filename": "5-dmin-2020.pdf",
            "href": "/api/degree-plans/file/2020/5-dmin-2020.pdf"
          },
          {
            "title": "Doctor of Philosophy in Biblical Studies (PhD)",
            "filename": "5-phd-bs-2020.pdf",
            "href": "/api/degree-plans/file/2020/5-phd-bs-2020.pdf"
          },
          {
            "title": "Doctor of Philosophy in Intercultural Studies (PhD)",
            "filename": "5-phd-is-2020.pdf",
            "href": "/api/degree-plans/file/2020/5-phd-is-2020.pdf"
          },
          {
            "title": "Master of Theology in Biblical Studies (ThM)",
            "filename": "5-thm-bs-2020.pdf",
            "href": "/api/degree-plans/file/2020/5-thm-bs-2020.pdf"
          },
          {
            "title": "Master of Theology in Intercultural Studies (ThM)",
            "filename": "5-thm-is-2020.pdf",
            "href": "/api/degree-plans/file/2020/5-thm-is-2020.pdf"
          },
          {
            "title": "Master of Theology in Theological Studies (ThM)",
            "filename": "5-thm-ts-2020.pdf",
            "href": "/api/degree-plans/file/2020/5-thm-ts-2020.pdf"
          }
        ]
      }
    ]
  }
] as DegreePlanYear[]
